baseURL = "https://heo-aio.github.io/"
languageCode = "ko-kr"
title = "heo_99의 블로그"

theme = "PaperMod"

[pagination]
pagerSize = 10

[params]
defaultTheme = "auto"
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowToc = true

#################
# 홈 화면 (기본 블로그형)
#################
[params.homeInfoParams]
Title = "heo_99"
Content = """
<img src="/images/zzangu.jpg" width="160" style="border-radius: 50%;" />

AI 개발자 취업 준비 | CS / SQL / AI 정리
"""


#################
# 소셜 링크
#################

[[params.socialIcons]]
name = "github"
url = "https://github.com/heo-aio"

[[params.socialIcons]]
name = "link"
url = "https://app.notion.com/p/Project-352bca91a4b98010beaef9641b01051c"

[[params.socialIcons]]
name = "email"
url = "mailto:ppp978597@gmail.com"

#################
# 메뉴
#################

[[menu.main]]
name = "Categories"
url = "/categories/"
weight = 10

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 20

#################
# Taxonomies
#################

[taxonomies]
category = "categories"
tag = "tags"