baseURL = "https://heo-aio.github.io/"
languageCode = "ko-kr"
title = "heo_99의 블로그"

theme = "PaperMod"

[pagination]
pagerSize = 10

[params]
defaultTheme = "auto"
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowToc = true

#################
# 프로필 (홈 화면)
#################
[params.profileMode]
enabled = true
title = "heo_99"
subtitle = "AI 개발자 취업 준비 | CS / SQL / AI 정리"
imageUrl = "images/zzangu.jpg"
imageWidth = 150
imageHeight = 150

[[params.profileMode.buttons]]
name = "Categories"
url = "/categories/"

[[params.profileMode.buttons]]
name = "Tags"
url = "/tags/"

#################
# 메뉴
#################

[[menu.main]]
name = "Categories"
url = "/categories/"
weight = 10

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 20

#################
# Taxonomies
#################

[taxonomies]
category = "categories"
tag = "tags"